function Hd = fdafunc
%FDAFUNC_FIRDIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 24-Oct-2016 13:15:07

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in kHz.
Fs = 96;  % Sampling Frequency

N    = 511;      % Order
Fc1  = 0.1;      % First Cutoff Frequency
Fc2  = 3.7;      % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
